#!/usr/bin/env python3
"""
Touchstone S-Parameter File Generator
LightRail AI LR-P3A Rev 6.3 — Quantum Photonic Accelerator

Generates analytical S-parameter models (.s2p, .s4p) for key QPA RF
structures, suitable for import into:
  - Ansys HFSS (verification / co-simulation)
  - Ansys SIwave (channel simulation)
  - Lumerical INTERCONNECT (photonic-electronic co-simulation)
  - Keysight ADS / Cadence Virtuoso
  - Any SPICE simulator with Touchstone support

Output files:
  TFLN_CPW_50ohm_100GHz.s2p     — 2-port CPW transmission line
  TFLN_MZI_Optical_2x2.s2p      — 2-port MZI optical transfer function
  CXL_Diff_Pair_85ohm.s4p       — 4-port CXL 2.0 differential pair
  LVDS_Trigger_100ohm.s2p       — 2-port LVDS trigger channel

Usage:
    python3 generate_sparams.py
"""

import numpy as np
import os

OUTPUT_DIR = os.path.dirname(os.path.abspath(__file__))


def write_touchstone_s2p(filepath, freqs_ghz, s11, s21, s12, s22,
                         z0=50.0, comment=""):
    """Write a Touchstone v1 .s2p file (2-port, complex S-parameters)."""
    with open(filepath, "w") as f:
        f.write(f"! Touchstone S2P File\n")
        f.write(f"! LightRail AI LR-P3A Rev 6.3 — QPA\n")
        if comment:
            f.write(f"! {comment}\n")
        f.write(f"! Generated by generate_sparams.py\n")
        f.write(f"!\n")
        f.write(f"# GHz S RI R {z0:.1f}\n")
        f.write(f"! freq        Re(S11)     Im(S11)     "
                f"Re(S21)     Im(S21)     "
                f"Re(S12)     Im(S12)     "
                f"Re(S22)     Im(S22)\n")
        for i in range(len(freqs_ghz)):
            f.write(f"{freqs_ghz[i]:12.4f}  "
                    f"{s11[i].real:12.6f} {s11[i].imag:12.6f}  "
                    f"{s21[i].real:12.6f} {s21[i].imag:12.6f}  "
                    f"{s12[i].real:12.6f} {s12[i].imag:12.6f}  "
                    f"{s22[i].real:12.6f} {s22[i].imag:12.6f}\n")
    print(f"  Generated: {filepath}")


def write_touchstone_s4p(filepath, freqs_ghz, s_matrix, z0=50.0, comment=""):
    """Write a Touchstone v1 .s4p file (4-port)."""
    n_freq = len(freqs_ghz)
    with open(filepath, "w") as f:
        f.write(f"! Touchstone S4P File\n")
        f.write(f"! LightRail AI LR-P3A Rev 6.3 — QPA\n")
        if comment:
            f.write(f"! {comment}\n")
        f.write(f"!\n")
        f.write(f"# GHz S RI R {z0:.1f}\n")
        for i in range(n_freq):
            f.write(f"! f = {freqs_ghz[i]:.4f} GHz\n")
            S = s_matrix[i]
            # Row 1: S11 S12 S13 S14
            f.write(f"{freqs_ghz[i]:12.4f}")
            for j in range(4):
                f.write(f"  {S[0,j].real:12.6f} {S[0,j].imag:12.6f}")
            f.write("\n")
            # Rows 2-4
            for r in range(1, 4):
                f.write(f"             ")
                for j in range(4):
                    f.write(f"  {S[r,j].real:12.6f} {S[r,j].imag:12.6f}")
                f.write("\n")
    print(f"  Generated: {filepath}")


def generate_cpw_sparam():
    """Generate S-parameters for 50-ohm TFLN CPW (1-120 GHz).

    Models a lossy transmission line on TFLN substrate:
      - Z0 = 50 ohm (CPW on LiNbO3, er_eff ~ 17)
      - Loss: 0.5 dB/mm at 100 GHz (conductor + dielectric)
      - Length: 5 mm (DAC to TFLN electrode routing)
    """
    freqs = np.linspace(1.0, 120.0, 120)  # 1-120 GHz, 1 GHz step

    z0 = 50.0
    length_mm = 5.0
    er_eff = 17.0
    c0 = 3e8  # m/s

    # Propagation constant
    alpha_base = 0.5 / 8.686  # 0.5 dB/mm → Np/mm at 100 GHz
    alpha = alpha_base * np.sqrt(freqs / 100.0)  # freq-dependent loss
    beta = 2 * np.pi * freqs * 1e9 / c0 * np.sqrt(er_eff) * 1e-3  # rad/mm

    gamma = alpha + 1j * beta  # complex propagation constant (per mm)

    # S-parameters for lossy transmission line
    s21 = np.exp(-gamma * length_mm)
    s12 = s21  # reciprocal
    s11 = np.zeros_like(freqs, dtype=complex)  # matched termination
    s22 = np.zeros_like(freqs, dtype=complex)

    # Add small reflection from discontinuities
    s11 = 0.02 * np.exp(-1j * 2 * beta * length_mm)
    s22 = 0.02 * np.exp(-1j * 2 * beta * length_mm)

    write_touchstone_s2p(
        os.path.join(OUTPUT_DIR, "TFLN_CPW_50ohm_100GHz.s2p"),
        freqs, s11, s21, s12, s22, z0=50.0,
        comment="50-ohm CPW on TFLN substrate, 5mm length, 1-120 GHz"
    )


def generate_mzi_optical_sparam():
    """Generate optical S-parameters for MZI 2x2 coupler.

    Models the MZI as a 2-port optical device at 1550 nm:
      - Frequency axis represents optical detuning from 193.1 THz
      - S21 = MZI transfer function (bar state)
      - S11 = back-reflection (very low for TFLN)
      - Insertion loss: 0.4 dB per MZI node
      - FSR: ~4 nm for 500 um arm length
    """
    # Optical frequency range: 192-194 THz (1546-1562 nm)
    # Mapped to "GHz" offset from 193.1 THz for Touchstone compatibility
    freq_offset_ghz = np.linspace(-500, 500, 201)  # +/- 500 GHz

    # MZI parameters
    arm_length = 500e-6  # 500 um
    n_eff = 2.211
    n_group = 2.35
    delta_L = 0  # balanced MZI (no arm length difference)
    IL = 0.4  # dB insertion loss
    theta = 0.42 * np.pi  # phase bias (from mesh compiler)

    c0 = 3e8
    f0 = 193.1e12  # center frequency (Hz)

    # MZI transfer function
    delta_f = freq_offset_ghz * 1e9  # Hz
    phase = 2 * np.pi * n_group * arm_length / c0 * delta_f + theta

    # Bar and cross port transmission
    t_bar = np.cos(phase / 2) ** 2
    t_cross = np.sin(phase / 2) ** 2

    # Apply insertion loss
    il_linear = 10 ** (-IL / 20)
    s21 = np.sqrt(t_bar) * il_linear * np.exp(1j * phase / 2)
    s11 = 0.001 * np.ones_like(freq_offset_ghz, dtype=complex)  # -60 dB reflection
    s12 = s21
    s22 = s11

    write_touchstone_s2p(
        os.path.join(OUTPUT_DIR, "TFLN_MZI_Optical_2x2.s2p"),
        freq_offset_ghz + 193100,  # absolute frequency in GHz
        s11, s21, s12, s22, z0=1.0,  # Z0=1 for optical (normalized)
        comment="MZI 2x2 optical transfer, 500um arms, theta=0.42pi, "
                "freq axis = optical THz"
    )


def generate_cxl_diff_sparam():
    """Generate 4-port S-parameters for CXL 2.0 differential pair.

    Models a 85-ohm differential pair on Megtron-7:
      - Zdiff = 85 ohm
      - Zodd = 42.5 ohm
      - Loss: 0.8 dB/inch at 32 GHz (PCIe Gen 6 fundamental)
      - Length: 100 mm (FPGA to CXL switch routing)
      - FEXT/NEXT crosstalk from adjacent pairs
    """
    freqs = np.linspace(0.1, 64.0, 128)  # 0.1-64 GHz

    z0 = 42.5  # odd-mode impedance (half of differential)
    length_inch = 3.94  # 100 mm
    er_eff = 3.1  # Megtron-7 effective

    c0 = 3e8 * 39.37  # m/s to inch/s

    # Loss model (Djordjevic-Sarkar)
    alpha_dc = 0.05  # Np/inch DC resistance
    alpha_skin = 0.15 * np.sqrt(freqs / 10.0)  # skin effect
    alpha_diel = 0.08 * freqs / 10.0  # dielectric loss (tan_d = 0.002)
    alpha = alpha_dc + alpha_skin + alpha_diel

    beta = 2 * np.pi * freqs * 1e9 / c0 * np.sqrt(er_eff)
    gamma = alpha + 1j * beta

    # 4-port S-matrix: [P1+, P1-, P2+, P2-]
    # Differential mode transmission
    s_matrix = np.zeros((len(freqs), 4, 4), dtype=complex)

    s_thru = np.exp(-gamma * length_inch)
    s_refl = 0.01 * np.exp(-1j * 2 * beta * length_inch)

    # Crosstalk (NEXT and FEXT)
    next_coupling = -45  # dB
    fext_coupling = -35  # dB
    s_next = 10 ** (next_coupling / 20) * np.exp(1j * np.pi / 4)
    s_fext = 10 ** (fext_coupling / 20) * s_thru * 0.1

    for i in range(len(freqs)):
        S = np.zeros((4, 4), dtype=complex)
        # Port 1+ to Port 2+ (differential thru)
        S[0, 2] = s_thru[i]
        S[2, 0] = s_thru[i]
        # Port 1- to Port 2- (differential thru)
        S[1, 3] = s_thru[i]
        S[3, 1] = s_thru[i]
        # Reflections
        S[0, 0] = s_refl[i]
        S[1, 1] = s_refl[i]
        S[2, 2] = s_refl[i]
        S[3, 3] = s_refl[i]
        # NEXT (near-end crosstalk: + to -)
        S[0, 1] = s_next
        S[1, 0] = s_next
        S[2, 3] = s_next
        S[3, 2] = s_next
        # FEXT (far-end crosstalk)
        S[0, 3] = s_fext[i]
        S[3, 0] = s_fext[i]
        S[1, 2] = s_fext[i]
        S[2, 1] = s_fext[i]
        s_matrix[i] = S

    write_touchstone_s4p(
        os.path.join(OUTPUT_DIR, "CXL_Diff_Pair_85ohm.s4p"),
        freqs, s_matrix, z0=42.5,
        comment="CXL 2.0 differential pair, 85ohm Zdiff, 100mm on Megtron-7"
    )


def generate_lvds_sparam():
    """Generate S-parameters for LVDS trigger channel.

    Models 100-ohm differential LVDS from FPGA to DAC:
      - Zdiff = 100 ohm
      - Data rate: 500 Mbps DDR (250 MHz fundamental)
      - Length: 30 mm (short run, FPGA to adjacent DAC)
      - Low loss at these frequencies
    """
    freqs = np.linspace(0.01, 5.0, 100)  # 10 MHz to 5 GHz

    z0 = 50.0  # odd-mode
    length_mm = 30.0
    er_eff = 3.1

    c0 = 3e8 * 1e-3  # m/s to mm/s... actually let's use proper units
    c0_mm = 3e11  # mm/s

    alpha = 0.002 * np.sqrt(freqs / 1.0)  # very low loss at <5 GHz
    beta = 2 * np.pi * freqs * 1e9 / c0_mm * np.sqrt(er_eff)
    gamma = alpha + 1j * beta

    s21 = np.exp(-gamma * length_mm)
    s12 = s21
    s11 = 0.005 * np.exp(-1j * 2 * beta * length_mm)
    s22 = s11

    write_touchstone_s2p(
        os.path.join(OUTPUT_DIR, "LVDS_Trigger_100ohm.s2p"),
        freqs, s11, s21, s12, s22, z0=50.0,
        comment="LVDS trigger channel, 100ohm diff, 30mm on Megtron-7"
    )


if __name__ == "__main__":
    print("Generating Touchstone S-parameter files...")
    print(f"Output directory: {OUTPUT_DIR}")
    print()

    generate_cpw_sparam()
    generate_mzi_optical_sparam()
    generate_cxl_diff_sparam()
    generate_lvds_sparam()

    print()
    print("Done. S-parameter files ready for import into:")
    print("  - Ansys HFSS / SIwave")
    print("  - Lumerical INTERCONNECT")
    print("  - Keysight ADS")
    print("  - Any Touchstone-compatible tool")
